[tox]
requires =
    tox>=4
env_list =
    clean
#    copydata
    py{311,312,313}
    lint
    type
    docs
    report

[testenv]
description = run the tests with pytest
skip_install = true
allowlist_externals = poetry
depends =
    py{311,312,313}: clean
commands_pre = 
    poetry install
commands =
    poetry run pytest -v -s --cov --cov-append --cov-report=term-missing {posargs:tests}

[testenv:clean]
description = cleans previous coverge reports
skip_install = true
allowlist_externals =
    poetry
commands_pre =
    poetry install
commands =
    coverage erase

[testenv:report]
description = prints out code coverage report
depends = py{311,312,313}
skip_install = true
commands_pre = 
    poetry install
commands =
    coverage report
    coverage html

#[testenv:copydata]
#description = copies external data files into project data directory
#skip_install = true
#allowlist_externals =
#    poetry
#    cp
#commands_pre =
#    poetry install
#commands =
#    cp ../DataFiles/TimeCons/EOP.mat data/EOP.mat
#    cp ../DataFiles/TimeCons/LeapSeconds.mat data/LeapSeconds.mat
#    cp ../DataFiles/TimeCons/time_constants.dat data/time_constants.dat

[testenv:lint]
description = run linter
skip_install = true
allowlist_externals = poetry
commands_pre = 
    poetry install
commands =
    poetry run ruff check {posargs:src tests}

[testenv:type]
description = run type checks
skip_install = true
allowlist_externals = poetry
commands_pre =
    poetry install
commands = poetry run mypy {posargs:src tests}

[testenv:docs]
description = auto generate output documents
depends = clean
skip_install = true
allowlist_externals =
    rm
    poetry
    bash
    rmdir
commands_pre =
    poetry install
commands =
    rm -rf docs
    poetry run pdoc --html --output-dir docs cara_analysis_tools
    bash -c 'mv docs/cara_analysis_tools/* docs'
    rmdir docs/cara_analysis_tools